### ISSUE TITLE
CAS updates in PR #1578 missing from cas.php in 2.12.1

### ISSUE THREAD

**Issue by wsams** [OCSInventory-NG/OCSInventory-Docker-Image#115]
I'm trying to use the image `ocsinventory/ocsinventory-docker-image:2.12.1` which contains this [`cas.php`](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/blob/2.12.1/backend/AUTH/methode/cas.php) file. However, [this change](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/1578) or another may be missing from the 2.12.1 release.

It's throwing this error,

```
[php:error] [pid 188] [client 192.168.1.6:58426] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function phpCAS::client(), 4 passed in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/cas.php on line 46 and at least 5 expected in /usr/share/ocsinventory-reports/ocsreports/vendor/jasig/phpcas/source/CAS.php:348\nStack trace:\n#0 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/cas.php(46): phpCAS::client()\n#1 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/auth.php(48): require_once('...')\n#2 /usr/share/ocsinventory-reports/ocsreports/require/header.php(321): require_once('...')\n#3 /usr/share/ocsinventory-reports/ocsreports/index.php(44): require('...')\n#4 {main}\n  thrown in /usr/share/ocsinventory-reports/ocsreports/vendor/jasig/phpcas/source/CAS.php on line 348
```

**Comment by wsams** [comment]
It looks like https://github.com/OCSInventory-NG/OCSInventory-ocsreports/blob/fd7926c9af211dfb1d3822d4809dca0f15584bb6/composer.json#L17 pulled in at least phpCAS 1.6.0 with `client` which requires 5 args.

**Comment by percu** [comment]
After upgrading to 2.12.2 everything is working fine again
